# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "continue/kickstart-flavor-gaia:testing"
config_file:
  template: "config.php.dist"
  target: "config.php"
command:
  init:
    - "composer install"

  test:
    - "./vendor/bin/tester -p /usr/bin/php -c test/php.ini -s ./test/**/**"